spring:
  application:
    name: ${APPLICATION_NAME:peregrinus}
  data:
    mongodb:
      host: localhost
      #      port: 27017
      #      username: changeit
      #      password: changeit
      database: peregrinus
  jackson:
    date-format: com.fasterxml.jackson.databind.util.ISO8601DateFormat
    default-property-inclusion: non_null
    property-naming-strategy: LOWER_CAMEL_CASE
    locale: de_DE
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: GMT

  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/certs

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    ROOT: info
    org.bremersee: debug
    reactor: debug
    org.springframework: info

bremersee:
  security:
    oauth2:
      password-flow:
        client-id: omnia
        client-secret: 2f586840-68df-4226-b105-397a56b2b4f2
        token-endpoint: https://openid.dev.bremersee.org/auth/realms/omnia/protocol/openid-connect/token
  exception-mapping:
    api-paths:
      - /api/**
